# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2d=arr.reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
arr1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr4.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [ ]:
arr5=np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
arr5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
arr6=np.array([ 0, 1, 2,3, 4, 5, 6, 7, 8, 9, 10, 11,12, 13, 14])
arr6.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
arr7=np.random.randn(5,5)
sqrt=np.square(arr7)
sqrt

array([[9.27088318e-01, 2.19195043e-01, 5.88334964e-01, 2.46212213e+00,
        1.58524841e-01],
       [2.54976586e-03, 3.01124005e-01, 1.01152666e+00, 6.98711585e-01,
        4.59367569e-01],
       [2.28353710e-01, 3.92305335e-02, 4.06655226e-01, 3.32666710e+00,
        3.15719776e-04],
       [1.83707867e+00, 4.69334675e-01, 1.36795265e+00, 2.32222152e-03,
        1.12105807e-01],
       [2.02974350e-01, 1.70927506e+00, 2.53010602e-01, 5.04867217e-01,
        5.75901453e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
arr=np.random.randn(5,6)
mean=np.mean(arr)
mean

-0.03654541736695785

## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
stnddev=arr.std()
stnddev

1.2598108575668507

## Question:10

### Find the median of the previous array in Q8?

In [ ]:
med=np.median(arr)
arr

array([[ 1.70148081, -0.65721745, -0.64564202, -2.13780993, -1.00012183,
         0.59669128],
       [-0.73724482, -1.32666042, -2.55946771, -0.37168347,  1.35906016,
         0.65346506],
       [-1.30027753,  1.10766452,  1.32185823,  2.03653549,  0.27817839,
         1.20491481],
       [-2.31519528,  0.80752549,  0.19797973, -0.50098051, -0.65211888,
        -1.36811291],
       [ 0.94131779,  1.56147378,  0.62027997,  1.53777499, -1.29540351,
        -0.15462676]])

## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
arr.T

array([[ 1.70148081, -0.73724482, -1.30027753, -2.31519528,  0.94131779],
       [-0.65721745, -1.32666042,  1.10766452,  0.80752549,  1.56147378],
       [-0.64564202, -2.55946771,  1.32185823,  0.19797973,  0.62027997],
       [-2.13780993, -0.37168347,  2.03653549, -0.50098051,  1.53777499],
       [-1.00012183,  1.35906016,  0.27817839, -0.65211888, -1.29540351],
       [ 0.59669128,  0.65346506,  1.20491481, -1.36811291, -0.15462676]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
import numpy as np
arr=np.random.randn(4,4)
dsum=arr.trace()
dsum

-2.013754254869264

## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
import numpy as np
arr=np.random.randn(4,4)
np.linalg.det(arr) 

0.18193918623387734

## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
per_5=np.percentile(arr,5)
per_5

-1.7678954463117675

In [ ]:
per_95=np.percentile(arr,95)
per_95

1.2530825506514527

## Question:15

### How to find if a given array has any null values?